# Generated by Django 3.2.8 on 2021-10-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('posts_id', models.AutoField(primary_key=True, serialize=False)),
                ('posts_caption', models.CharField(default='', max_length=500)),
                ('posts_image', models.ImageField(default='', upload_to='modell/images')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
