# Generated by Django 3.2.8 on 2021-10-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modell', '0002_auto_20211029_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', models.CharField(default='', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modell.comment')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modell.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modell.user')),
            ],
        ),
    ]
