# Generated by Django 3.2.8 on 2021-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modell', '0003_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='bio_id',
        ),
        migrations.AddField(
            model_name='bio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
