# Generated by Django 3.2.8 on 2021-11-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modell', '0004_auto_20211101_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modell.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
